train:
  batch_size: 8
  shuffle: True
  num_workers: 8
  drop_last: True
  pin_memory: True

valid:
  batch_size: 8
  shuffle: False
  num_workers: 8
  drop_last: False
  pin_memory: True

test:
  batch_size: 8
  shuffle: False
  num_workers: 8
  drop_last: False
  pin_memory: True

predict:
  batch_size: 8
  shuffle: False
  num_workers: 8
  drop_last: False
  pin_memory: True
