_target_: src.datamodules.daic_datamodules.DaicDataModule

defaults:
  - _self_
  - loaders: daic.yaml
  - transforms: audio.yaml

# Choose labels tensor type in dataset based on loss type you use, e.g.:
# - torch.nn.BCEWithLogitsLoss requires torch.FloatTensor
# - torch.nn.CrossEntropyLoss requires torch.LongTensor

datasets:
  train:
    _target_: src.datamodules.daic_datasets.DaicDataset
    json_path: ${paths.data_dir}/daic-woz/annotation.json
    data_path: ${paths.data_dir}/daic-woz/raw
    label_type: "torch.FloatTensor"

  valid:
    _target_: src.datamodules.daic_datasets.DaicDataset
    json_path: ${paths.data_dir}/daic-woz/annotation.json
    data_path: ${paths.data_dir}/daic-woz/raw
    label_type: "torch.FloatTensor"

  test:
    _target_: src.datamodules.daic_datasets.DaicDataset
    json_path: ${paths.data_dir}/daic-woz/annotation.json
    data_path: ${paths.data_dir}/daic-woz/raw
    label_type: "torch.FloatTensor"

  # predict:
  #   dataset1:
  #     _target_: src.datamodules.datasets.ClassificationDataset
  #     json_path: ${paths.data_dir}/predict/data1.json
  #     label_type: "torch.FloatTensor"
  #   dataset2:
  #     _target_: src.datamodules.datasets.ClassificationDataset
  #     json_path: ${paths.data_dir}/predict/data2.json
  #     label_type: "torch.FloatTensor"
